export const SIGNIN = 'SIGNIN';
export const CREATEADDRESS = 'CREATEADDRESS'
export const FETCHCATEGORY = 'FETCHCATEGORY'
export const USERINFO = 'USERINFO'
export const ADD_TO_CART = 'ADD_TO_CART'
export const INCREASE_QUANTITY = 'INCREASE_QUANTITY'
export const DECREASE_QUANTITY = 'DECREASE_QUANTITY'
export const REMOVE_ITEM_FROM_CART = 'REMOVE_ITEM_FROM_CART'